url: https://k8s.community  # with the https protocol
enforce_ssl: k8s.community  # without any protocol
theme: jekyll-theme-slate
title: [k8s.community]
description: [Про Kubernetes по-русски]
github:
  repository_url: https://github.com/k8s-community
